# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         SQL-Shell
version:      1.13
version_from: lib/SQL/Shell.pm
installdirs:  site
requires:
    DBI:                           0
    IO::CaptureOutput:             0
    Log::Trace:                    0
    Test::Assertions:              0
    Test::Assertions::TestScript:  0
    URI::Escape:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
